name: orchestrator
description: A Dart package which can be used to programatically generate Dart code.
version: 0.2.0
repository: https://github.com/YouriLieverdink/orchestrator

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  dart_style: ^2.2.3

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.4
